"""Reflects columns to rows in pairwise RMSD matricies generated by pwrmsd_writer_mulitnode.py,
after merging all individual cycle dataframes.
"""

import pandas as pd
from os.path import *
import time
import glob

def df_concat(ID, ADD, max_cycle=1000):
    """Merges all per cycle dataframes of pairwise rmsds into one dataframe.
    """
    df = pd.DataFrame()
    cycles = ['%04d' % x for x in range(1, max_cycle+1)]
    for cyc in cycles:
        if int(cyc) % 100 == 0:
            print(cyc)
        piecedf = pd.read_pickle(abspath(f'pwRMSD/{ID}_{ADD}_cycle{cyc}_pwrmsd.pkl'))
        df = df.append(piecedf, ignore_index=True)
    return df

def reflect_mtrx(df, ID, ADD):
    for i in range(len(df.columns)):
        df[i] = df.loc[i]
    df.to_pickle(f'pwRMSD/{ID}_{ADD}_50k_50k_reflect.pkl')

if __name__ == '__main__':
    from time import time
    start = time()
    

    ID = #ID used in pwrmsd_writer_mulitnode.py, e.g. an inchi key 'WWUZIQQURGPMPG-CCEZHUSRSA-N'
    ADD = # e.g. '+H'

    df = df_concat(ID, ADD)
    reflect_mtrx(df, ID, ADD)

    print(time()-start)
